export const BangumiExtraInfoKeyMap: Record<string, string> = {
  生日: 'birthday',
  引用来源: 'source',
  twitter: 'twitter',
  主页: 'homepage',
  官方网站: 'official_website',
  母公司: 'parent_company',
  剧本: 'script',
  原作: 'original_work',
  原画: 'original_art',
  SD原画: 'sd_original_art',
  CG: 'cg_artists',
  'C G': 'cg_artists',
  Logo设计: 'logo_design',
  UI: 'ui_design',
  设计: 'design',
  人物设定: 'character_design',
  设定协力: 'setting_cooperation',
  企划: 'project',
  企画: 'project',
  企划协力: 'project_cooperation',
  企画协力: 'project_cooperation',
  导演: 'director',
  制作人: 'producer',
  背景: 'background',
  协力: 'cooperation',
  发行: 'publish',
  音乐: 'music',
  主题歌作词: 'theme_song_lyrics',
  主题歌作曲: 'theme_song_composition',
  主题歌演出: 'theme_song_performance',
  音响监督: 'sound_director',
  动画制作: 'animation_production',
  程序: 'programming',
}
